six2:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '102817'
  office_ids: 'FTO'
  query_code: '1981'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six1:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '531352'
  office_ids: ''
  query_code: '1977'
  select_days: '2023-07-08,2023-07-15'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six7:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: 'S548304'
  office_ids: 'RHK'
  query_code: '2012'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: ''
  weekdays: ''
six8:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '424517'
  office_ids: 'TMO'
  query_code: '2011'
  select_days: '2023-07-28'
  start_day: '2023-05-01'
  time_intervals: '0700,1200'
  weekdays: ''
six14:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: 'S453006'
  office_ids: 'FTO'
  query_code: '2011'
  select_days: '2023-07-11'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six23:
  day_intervals: '2023-07-17,2023-07-30'
  end_day: '2023-08-01'
  id_code: 'S234183'
  office_ids: 'FTO,TMO,YLO'
  query_code: '2011'
  select_days: ''
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six27:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '495458'
  office_ids: 'TMO'
  query_code: '1988'
  select_days: '2023-06-23'
  start_day: '2023-06-01'
  time_intervals: '1300,2345'
  weekdays: ''
six30:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: 'S408005'
  office_ids: 'FTO'
  query_code: '0730'
  select_days: '2023-07-11'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six20:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: '835557'
  office_ids: ''
  query_code: '1984'
  select_days: '2023-06-24'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six33:
  day_intervals: 2023-07-08,2023-08-09
  exclude_days: 2023-07-28,2023-07-27
  id_code: '456135'
  office_ids: ''
  query_code: '2001'
  select_days: ''
  time_intervals: 1300,1800
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
six34:
  day_intervals: 2023-06-19,2023-07-14
  exclude_days: ''
  id_code: '964447'
  office_ids: ''
  query_code: '1989'
  select_days: ''
  time_intervals: ''
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
six35:
  day_intervals: 2023-09-01,2023-09-30
  exclude_days: ''
  id_code: '234027'
  office_ids: ''
  query_code: '1998'
  select_days: ''
  time_intervals: ''
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
six37:
  day_intervals: 2023-06-13,2023-07-14
  exclude_days: ''
  id_code: 'S481942'
  office_ids: ''
  query_code: '2011'
  select_days: ''
  time_intervals: ''
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
six36:
  day_intervals: '2023-06-19,2023-06-30'
  exclude_days: '2023-06-20,2023-06-27'
  id_code: '264550'
  office_ids: ''
  query_code: '1984'
  select_days: '2023-09-12,2023-09-09,2023-09-08,2023-09-06,2023-09-05,2023-09-02,2023-09-01'
  time_intervals: ''
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
six38:
  day_intervals: '2023-06-23,2023-06-24'
  exclude_days: ''
  id_code: '477570'
  office_ids: ''
  query_code: '1976'
  select_days: ''
  time_intervals: ''
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
tb1:
  day_intervals: ''
  end_day: '2023-07-31'
  id_code: '436963'
  office_ids: ''
  query_code: '8888'
  select_days: '2023-07-22'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
daa:
  day_intervals: ''
  end_day: '2023-07-31'
  id_code: '692290'
  office_ids: 'RHK,RKO,FTO,TMO,YLO'
  query_code: '8888'
  select_days: '2023-07-03'
  start_day: '2023-06-01'
  time_intervals: '1115,2345'
  weekdays: ''
elsa:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '007606'
  office_ids: ''
  query_code: '0716'
  select_days: '2023-06-17'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
eric:
  day_intervals: ''
  end_day: '2023-07-10'
  id_code: '747834'
  office_ids: ''
  query_code: '2486'
  select_days: '2023-07-06,2023-07-07'
  start_day: '2023-07-01'
  time_intervals: ''
  weekdays: ''
Paul1:
  day_intervals: ''
  end_day: '2023-12-10'
  exclude_days: ''
  id_code: '863097'
  office_ids: RHK,RKO
  query_code: '0425'
  select_days: '2023-08-26'
  start_day: '2023-05-01'
  time_intervals: ''
  weekdays: ''
Paul2:
  day_intervals: ''
  end_day: '2023-12-10'
  exclude_days: ''
  id_code: '863097'
  office_ids: RHK,RKO
  query_code: '0425'
  select_days: '2023-08-28'
  start_day: '2023-05-01'
  time_intervals: 0700,1200
  weekdays: ''
fangping1:
  end_day: '2023-12-10'
  start_day: '2023-05-01'
  day_intervals: ''
  exclude_days: ''
  id_code: '212019'
  office_ids: RHK
  query_code: '7890'
  select_days: '2023-07-06'
  time_intervals: 1600,2345
  weekdays: ''
fangping2:
  end_day: '2023-12-10'
  start_day: '2023-05-01'
  day_intervals: ''
  exclude_days: ''
  id_code: '212019'
  office_ids: RHK
  query_code: '7890'
  select_days: 2023-07-07,2023-07-08
  time_intervals: ''
  weekdays: ''
liyue:
  day_intervals: ''
  exclude_days: ''
  id_code: '067966'
  office_ids: ''
  query_code: '0809'
  select_days: '2023-06-30'
  time_intervals: ''
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
baijing1:
  day_intervals: ''
  exclude_days: ''
  id_code: '827477'
  office_ids: 'RHK,RKO,RKT,FTO'
  query_code: '2017'
  select_days: '2023-06-27'
  time_intervals: '1300,2345'
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
baijing2:
  day_intervals: ''
  exclude_days: ''
  id_code: '827477'
  office_ids: 'RHK,RKO,RKT,FTO'
  query_code: '2017'
  select_days: '2023-06-28'
  time_intervals: ''
  weekdays: ''
  end_day: '2023-12-10'
  start_day: '2023-05-01'
