my:
  day_intervals: '2023-07-01,2023-09-30'
  end_day: '2023-10-01'
  id_code: '666666'
  office_ids: ''
  query_code: '0721'
  select_days: '2023-06-08'
  start_day: '2023-05-01'
  time_intervals: ''
  weekdays: ''