six2:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '102817'
  office_ids: 'FTO'
  query_code: '1981'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six1:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '531352'
  office_ids: ''
  query_code: '1977'
  select_days: '2023-07-08'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six6:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: 'S581581'
  office_ids: 'RHK'
  query_code: '2012'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: ''
  weekdays: ''
six7:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: 'S548304'
  office_ids: 'RHK'
  query_code: '2012'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: ''
  weekdays: ''
six8:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '424517'
  office_ids: 'TMO'
  query_code: '2011'
  select_days: '2023-07-28'
  start_day: '2023-05-01'
  time_intervals: '0700,1200'
  weekdays: ''
six10:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '321382'
  office_ids: 'RHK'
  query_code: '0326'
  select_days: '2023-08-21'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six13:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '271203'
  office_ids: 'YLO'
  query_code: '1998'
  select_days: '2023-06-20'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six11:
  day_intervals: '2023-07-08,2023-07-11'
  end_day: '2023-10-01'
  id_code: 'S408005'
  office_ids: 'FTO,TMO,YLO'
  query_code: '0730'
  select_days: '2023-07-06'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six14:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: 'S453006'
  office_ids: 'FTO'
  query_code: '2011'
  select_days: '2023-07-11'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six9:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '271203'
  office_ids: ''
  query_code: '1998'
  select_days: '2023-06-18,2023-06-19,2023-06-20,2023-06-21'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six16:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: '806818'
  office_ids: 'RHK'
  query_code: '1990'
  select_days: '2023-06-19,2023-06-20,2023-06-21,2023-06-22,2023-06-23,2023-06-24'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six17:
  day_intervals: '2023-07-10,2023-07-14'
  end_day: '2023-08-01'
  id_code: '763926'
  office_ids: ''
  query_code: '1997'
  select_days: ''
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six18:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: 'S381160'
  office_ids: ''
  query_code: '8181'
  select_days: '2023-06-20'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six19:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: 'S381160'
  office_ids: ''
  query_code: '8181'
  select_days: '2023-06-21'
  start_day: '2023-06-01'
  time_intervals: '0700,1145'
  weekdays: ''
six22:
  day_intervals: '2023-07-10,2023-07-15'
  end_day: '2023-08-01'
  id_code: 'S496624'
  office_ids: 'FTO,TMO,YLO'
  query_code: '2011'
  select_days: ''
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six23:
  day_intervals: '2023-07-17,2023-07-30'
  end_day: '2023-08-01'
  id_code: 'S234183'
  office_ids: 'FTO,TMO,YLO'
  query_code: '2011'
  select_days: ''
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six24:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: '596246'
  office_ids: ''
  query_code: '1990'
  select_days: '2023-06-14,2023-06-15'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six25:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '668590'
  office_ids: 'RKO'
  query_code: '1979'
  select_days: '2023-06-21'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six26:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '899308'
  office_ids: ''
  query_code: '8888'
  select_days: '2023-06-23'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six27:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '495458'
  office_ids: 'TMO'
  query_code: '1988'
  select_days: '2023-06-23'
  start_day: '2023-06-01'
  time_intervals: '1300,2345'
  weekdays: ''
six30:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: 'S408005'
  office_ids: 'FTO'
  query_code: '0730'
  select_days: '2023-07-11'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six31:
  day_intervals: '2023-09-01,2023-09-10'
  end_day: '2023-10-01'
  id_code: '470500'
  office_ids: ''
  query_code: '1990'
  select_days: ''
  start_day: '2023-09-01'
  time_intervals: ''
  weekdays: ''
six21:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: 'M263962'
  office_ids: 'RHK'
  query_code: '1966'
  select_days: '2023-06-12'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
tb1:
  day_intervals: ''
  end_day: '2023-07-31'
  id_code: '436963'
  office_ids: ''
  query_code: '8888'
  select_days: '2023-07-22'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
daa:
  day_intervals: ''
  end_day: '2023-07-31'
  id_code: '692290'
  office_ids: 'RHK,RKO,FTO,TMO,YLO'
  query_code: '8888'
  select_days: '2023-07-03'
  start_day: '2023-06-01'
  time_intervals: '11:15,2345'
  weekdays: ''
six20:
  day_intervals: ''
  end_day: '2023-08-01'
  id_code: '835557'
  office_ids: ''
  query_code: '1984'
  select_days: '2023-06-24'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
six33:
  day_intervals: '2023-07-08,2023-08-09'
  end_day: '2023-10-01'
  id_code: '456135'
  office_ids: ''
  query_code: '2001'
  select_days: ''
  start_day: '2023-07-01'
  time_intervals: '1300,1800'
  weekdays: ''
elsa:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '007606'
  office_ids: ''
  query_code: '0716'
  select_days: '2023-06-17'
  start_day: '2023-06-01'
  time_intervals: ''
  weekdays: ''
