sentinal:
  day_intervals: ''
  id_code: '555555'
  office_ids: ''
  query_code: '0721'
  select_days: '2023-06-23,2023-06-24'
  exclude_days: '2023-06-23'
  time_intervals: ''
  weekdays: ''
  version: 0
  suspend: 0
six34:
  day_intervals: '2023-06-19,2023-07-14'
  id_code: '234567'
  office_ids: ''
  query_code: '1993'
  select_days: ''
  exclude_days: ''
  time_intervals: ''
  weekdays: ''
  version: 0
  suspend: 1