sentinal2:
  applicant: 155554,19930110
  book_type: other
  day_intervals: 2023-06-23,2023-10-31
  exclude_days: '2023-06-23'
  first_book: 1
  office_ids: ''
  query_code: '1993'
  select_days: ''
  suspend: 0
  thd_num: 1
  time_intervals: ''
  version: 0
  weekdays: ''