Jane1:
  applicant: M436971,19840105
  book_type: ''
  day_intervals: ''
  evisa: ''
  exclude_days: ''
  first_book: 0
  office_ids: RHK
  query_code: '0627'
  select_days: '2023-07-28'
  suspend: 0
  thd_num: 2
  time_intervals: 1745,2000
  version: 0
  weekdays: ''
Jane2:
  applicant: M436971,19840105
  book_type: ''
  day_intervals: ''
  evisa: ''
  exclude_days: ''
  first_book: 0
  office_ids: RHK
  query_code: '0627'
  select_days: '2023-07-29'
  suspend: 0
  thd_num: 2
  time_intervals: 1630,1700
  version: 0
  weekdays: ''
boba:
  applicant: 700842,00000000
  book_type: ''
  day_intervals: 2023-08-17,2023-08-30
  evisa: ''
  exclude_days: ''
  first_book: 0
  office_ids: ''
  query_code: '3511'
  select_days: ''
  suspend: 0
  thd_num: 4
  time_intervals: ''
  version: 0
  weekdays: ''
eric:
  applicant: 747834,00000000
  book_type: ''
  day_intervals: ''
  evisa: ''
  exclude_days: ''
  first_book: 0
  office_ids: 'RHK'
  query_code: '2486'
  select_days: '2023-07-06'
  suspend: 0
  thd_num: 4
  time_intervals: ''
  version: 0
  weekdays: ''
junjun:
  applicant: 113367,00000000
  book_type: ''
  day_intervals: ''
  evisa: ''
  exclude_days: ''
  first_book: 0
  office_ids: ''
  query_code: '0905'
  select_days: '2023-07-10'
  suspend: 0
  thd_num: 6
  time_intervals: ''
  version: 0
  weekdays: ''
six1:
  applicant: 380219,20120120
  book_type: 'other'
  day_intervals: ''
  evisa: ''
  exclude_days: ''
  first_book: 1
  office_ids: 'RHK'
  query_code: '2012'
  select_days: '2023-07-10'
  suspend: 0
  thd_num: 6
  time_intervals: ''
  version: 0
  weekdays: ''