sentinal:
  day_intervals: ''
  office_ids: ''
  query_code: '0721'
  select_days: '2023-06-23,2023-10-24'
  exclude_days: '2023-06-23'
  time_intervals: ''
  weekdays: ''
  version: 0
  suspend: 0
  thd_num: 1
  first_book: 0
  book_type: 'other'
  applicant: '555555,00000000'