Paul1:
  day_intervals: ''
  exclude_days: ''
  id_code: '863097'
  office_ids: RHK,RKO
  query_code: '0425'
  select_days: '2023-08-26'
  time_intervals: ''
  weekdays: ''
Paul2:
  day_intervals: ''
  exclude_days: ''
  id_code: '863097'
  office_ids: RHK,RKO
  query_code: '0425'
  select_days: '2023-08-28'
  time_intervals: 0700,1200
  weekdays: ''
bot2:
  day_intervals: ''
  exclude_days: ''
  id_code: '999999'
  office_ids: ''
  query_code: '1999'
  select_days: 2023-06-15,2023-06-14
  time_intervals: ''
  weekdays: ''
fangping1:
  day_intervals: ''
  exclude_days: ''
  id_code: '212019'
  office_ids: RHK
  query_code: '7890'
  select_days: '2023-07-06'
  time_intervals: 1600,2345
  weekdays: ''
fangping2:
  day_intervals: ''
  exclude_days: ''
  id_code: '212019'
  office_ids: RHK
  query_code: '7890'
  select_days: 2023-07-07,2023-07-08
  time_intervals: ''
  weekdays: ''
liyue:
  day_intervals: ''
  exclude_days: ''
  id_code: 067966
  office_ids: ''
  query_code: 0809
  select_days: '2023-06-30'
  time_intervals: ''
  weekdays: ''
sentinal:
  day_intervals: ''
  exclude_days: '2023-06-23'
  id_code: '555555'
  office_ids: ''
  query_code: '0721'
  select_days: 2023-06-23,2023-06-24
  time_intervals: ''
  weekdays: ''
six33:
  day_intervals: 2023-07-08,2023-08-09
  exclude_days: 2023-07-28,2023-07-27
  id_code: '456135'
  office_ids: ''
  query_code: '2001'
  select_days: ''
  time_intervals: 1300,1800
  weekdays: ''
