sentinal:
  day_intervals: ''
  id_code: '555555'
  office_ids: ''
  query_code: '0721'
  select_days: '2023-06-23,2023-06-24'
  exclude_days: '2023-06-23'
  time_intervals: ''
  weekdays: ''
six34:
  day_intervals: '2023-06-19,2023-07-14'
  id_code: '964447'
  office_ids: ''
  query_code: '1989'
  select_days: ''
  exclude_days: ''
  time_intervals: ''
  weekdays: ''
six35:
  day_intervals: '2023-09-01,2023-09-30'
  id_code: '234027'
  office_ids: ''
  query_code: '1998'
  select_days: ''
  exclude_days: ''
  time_intervals: ''
  weekdays: ''