sentinal:
  day_intervals: '2023-06-01,2023-06-30'
  id_code: 'M436971'
  office_ids: ''
  query_code: '0627'
  select_days: ''
  time_intervals: ''
  weekdays: ''
lijia1:
  day_intervals: ''
  id_code: '456986'
  office_ids: ''
  query_code: '1004'
  select_days: '2023-06-06'
  time_intervals: ''
  weekdays: ''
lijia2:
  day_intervals: '2023-06-06,2023-06-30'
  id_code: '456986'
  office_ids: ''
  query_code: '1004'
  select_days: ''
  time_intervals: '1915,2130'
  weekdays: '3'
lijia3:
    day_intervals: '2023-06-09,2023-07-01'
    id_code: '456986'
    office_ids: ''
    query_code: '1004'
    select_days: ''
    time_intervals: ''
    weekdays: ''