lijia1:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '456986'
  office_ids: ''
  query_code: '1004'
  select_days: '2023-06-13'
  start_day: '2023-05-01'
  time_intervals: '1330,2345'
  weekdays: ''
lijia2:
  day_intervals: ''
  end_day: '2023-07-01'
  id_code: '456986'
  office_ids: ''
  query_code: '1004'
  select_days: '2023-06-14'
  start_day: '2023-05-01'
  time_intervals: '0700,1630'
  weekdays: ''
six2:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '102817'
  office_ids: 'FTO'
  query_code: '1981'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six1:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '531352'
  office_ids: ''
  query_code: '1977'
  select_days: '2023-07-08'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six5:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '830696'
  office_ids: 'RKO'
  query_code: '8981'
  select_days: '2023-07-18'
  start_day: '2023-05-01'
  time_intervals: '0700,1230'
  weekdays: ''
six6:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: 'S581581'
  office_ids: 'RHK'
  query_code: '2012'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: ''
  weekdays: ''
six7:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: 'S548304'
  office_ids: 'RHK'
  query_code: '2012'
  select_days: '2023-07-03'
  start_day: '2023-05-01'
  time_intervals: ''
  weekdays: ''
six8:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '424517'
  office_ids: 'TMO'
  query_code: '2011'
  select_days: '2023-07-28'
  start_day: '2023-05-01'
  time_intervals: '0700,1200'
  weekdays: ''
six10:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '321382'
  office_ids: 'RHK'
  query_code: '0326'
  select_days: '2023-08-21'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''
six13:
  day_intervals: ''
  end_day: '2023-10-01'
  id_code: '271203'
  office_ids: 'YLO'
  query_code: '1998'
  select_days: '2023-06-20'
  start_day: '2023-05-01'
  time_intervals: '1300,2345'
  weekdays: ''

